name: action di giocy
on:
    push:                   #si può pure commentare a differenza del json... PE SI SSI MO
jobs:
    lavoroesempio:
        runs-on: ubuntu-latest
        steps: 
         - run: echo "davide lacerenza"
        

            
