name: Action di giocy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  train-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2024-26.ML-01/cerza
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          mdl.py
          
      - name: Save model artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: 2024-26.ML-01/cerza